### ISSUE TITLE
Can I remove padding around icon? 

### ISSUE THREAD

**Issue by PraktikerNeosoft** [nstudio/nativescript-floatingactionbutton#104]
Can I remove padding around icon? I want to use full width and max icn image. Thanx Miklos

**Comment by dosomder** [comment]
@bradmartin I need this too. On Android the problem seems to be
```
this.android.setScaleType(android.widget.ImageView.ScaleType.CENTER_INSIDE);
```
This prevents adjusting the size since it rescales the text / icon. Here is a playground demo: https://play.nativescript.org/?template=play-vue&id=Z14c56

Using
```
this.android.setScaleType(android.widget.ImageView.ScaleType.CENTER);
```
allows to freely set size and fixes the problem. This is what I need.
