### ISSUE TITLE
Calling js method onCreateView failed

### ISSUE THREAD

**Issue by jadedigital** [nstudio/nativescript-floatingactionbutton#105]
I'm using Nativescript Vue, and testing on Android.

Using:
CLI: 6.1.2
Runtime(s): tns-android: 'rc'

I've installed as per the readme, but I get the following error when I try to run:

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: android.content.res.Resources$NotFoundException: Resource ID #0x0
System.err:
System.err: StackTrace:
System.err: Fab.<computed>(file:///node_modules\@nstudio\nativescript-floatingactionbutton\fab.js:82:69)
System.err:     at applyAllNativeSetters(file:///node_modules\tns-core-modules\ui\core\properties\properties.js:1046:28)
System.err:     at initNativeView(file:///node_modules\tns-core-modules\ui\core\properties\properties.js:990:8)
System.err:     at ViewBase.onResumeNativeUpdates(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:628:21)
System.err:     at ViewBase._resumeNativeUpdates(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:273:17)
System.err:     at ViewBase.onLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:232:13)
System.err:     at View.onLoaded(file:///node_modules\tns-core-modules\ui\core\view\view.js:246:34)
System.err:     at FloatingActionButtonBase.onLoaded(file:///node_modules\@nstudio\nativescript-floatingactionbutton\fab-common.js:15:34)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:89)
System.err:     at ViewBase.callFunctionWithSuper(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:305:8)
System.err:     at ViewBase.callLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:13)
System.err:     at ViewBase.loadView(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:440:17)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:234:18)
System.err:     at LayoutBaseCommon.eachChildView(file:///node_modules\tns-core-modules\ui\layouts\layout-base-common.js:125:25)
System.err:     at ViewCommon.eachChild(file:///node_modules\tns-core-modules\ui\core\view\view-common.js:1010:13)
System.err:     at ViewBase.onLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:233:13)
System.err:     at View.onLoaded(file:///node_modules\tns-core-modules\ui\core\view\view.js:246:34)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:89)
System.err:     at ViewBase.callFunctionWithSuper(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:305:8)
System.err:     at ViewBase.callLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:13)
System.err:     at ViewBase.loadView(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:440:17)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:234:18)
System.err:     at ContentView.eachChildView(file:///node_modules\tns-core-modules\ui\content-view\content-view.js:70:12)
System.err:     at ViewCommon.eachChild(file:///node_modules\tns-core-modules\ui\core\view\view-common.js:1010:13)
System.err:     at ViewBase.onLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:233:13)
System.err:     at View.onLoaded(file:///node_modules\tns-core-modules\ui\core\view\view.js:246:34)
System.err:     at ScrollViewBase.onLoaded(file:///node_modules\tns-core-modules\ui\scroll-view\scroll-view-common.js:31:34)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:89)
System.err:     at ViewBase.callFunctionWithSuper(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:305:8)
System.err:     at ViewBase.callLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:13)
System.err:     at ViewBase.loadView(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:440:17)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:234:18)
System.err:     at ContentView.eachChildView(file:///node_modules\tns-core-modules\ui\content-view\content-view.js:70:12)
System.err:     at ViewCommon.eachChild(file:///node_modules\tns-core-modules\ui\core\view\view-common.js:1010:13)
System.err:     at ViewBase.onLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:233:13)
System.err:     at View.onLoaded(file:///node_modules\tns-core-modules\ui\core\view\view.js:246:34)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:89)
System.err:     at ViewBase.callFunctionWithSuper(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:305:8)
System.err:     at ViewBase.callLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:13)
System.err:     at ViewBase.loadView(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:440:17)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:234:18)
System.err:     at ContentView.eachChildView(file:///node_modules\tns-core-modules\ui\content-view\content-view.js:70:12)
System.err:     at PageBase.eachChildView(file:///node_modules\tns-core-modules\ui\page\page-common.js:126:39)
System.err:     at ViewCommon.eachChild(file:///node_modules\tns-core-modules\ui\core\view\view-common.js:1010:13)
System.err:     at ViewBase.onLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:233:13)
System.err:     at View.onLoaded(file:///node_modules\tns-core-modules\ui\core\view\view.js:246:34)
System.err:     at Page.onLoaded(file:///node_modules\tns-core-modules\ui\page\page.js:43:34)
System.err:     at (file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:89)
System.err:     at ViewBase.callFunctionWithSuper(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:305:8)
System.err:     at ViewBase.callLoaded(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:312:13)
System.err:     at ViewBase.loadView(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:440:17)
System.err:     at ViewBase._addViewCore(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:435:17)
System.err:     at ViewBase._addView(file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:421:13)
System.err:     at FragmentCallbacksImplementation.onCreateView(file:///node_modules\tns-core-modules\ui\frame\frame.js:687:18)
System.err:     at FragmentClass.onCreateView(file:///node_modules\tns-core-modules\ui\frame\fragment.js:26:37)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
System.err:     at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
System.err:     at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
System.err:     at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err:     at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
System.err:     at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
System.err:     at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
System.err:     at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7037)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
System.err: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
System.err:     at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:237)
System.err:     at android.content.res.Resources.getDrawableForDensity(Resources.java:902)
System.err:     at android.content.res.Resources.getDrawable(Resources.java:842)
System.err:     at android.content.res.Resources.getDrawable(Resources.java:817)
System.err:     ... 41 more

**Comment by jadedigital** [comment]
I got this fixed.
I think the issue was that I was trying to use an icon font for the icon. 
Switching to local file for the icon seems to have it working properly.

**Comment by manuelgeek** [comment]
> I got this fixed.
> I think the issue was that I was trying to use an icon font for the icon.
> Switching to local file for the icon seems to have it working properly.

this saved me
