### ISSUE TITLE
loadFromFontIconCode() is deprecated

### ISSUE THREAD

**Issue by tst69** [nstudio/nativescript-floatingactionbutton#112]
With `loadFromFontIconCode()` deprecated, would it be possible to update it to `fromFontIconCodeSync()` in [fab-common.ts](https://github.com/nstudio/nativescript-floatingactionbutton/blob/c7e60da5fcc2880cae514bb090a90c426f8751df/src/fab-common.ts#L198)? This will prevent the error logs.

**Comment by romislovs** [comment]
+1

**Comment by luiswill** [comment]
+ 1

**Comment by Klunk75** [comment]
+1

**Comment by bradmartin** [comment]
Would accept a PR if someone wants to contribute, should be fairly straight forward. If need any help, feel free to ping me.
