### ISSUE TITLE
Adapt icon to screen

### ISSUE THREAD

**Issue by wuilmerj24** [nstudio/nativescript-floatingactionbutton#113]
I have implemented in the fab button an image but the image does not adapt to the size of the screen
![WhatsApp Image 2020-04-03 at 9 24 28 PM](https://user-images.githubusercontent.com/7539995/78415798-1f8b9c00-75f2-11ea-82e0-6aca7110c1f6.jpeg)

**Comment by wuilmerj24** [comment]
??

**Comment by bradmartin** [comment]
did you correctly use density independent icons in the app_resources so that the images scale depending on the device screen? See the demo app for example and the NS docs should cover using `res://` for images to use density independent images.

**Comment by wuilmerj24** [comment]
@bradmartin Yes. Add each image in my res folder with the respective densities. But it still happens. Even download your demo project and the same thing happens.

**Comment by bradmartin** [comment]
Might be a device bug, never seen this on any device I have or any other reports. What device do you use? Could you check on some emulators and see if it occurs?

**Comment by wuilmerj24** [comment]
@bradmartin I have tested it on emulators with android and on my huawei p smart 2018 and they look the same. Even he copied the images from the res of android that are in the demo project and nothing.

**Comment by bradmartin** [comment]
![Screenshot_1586438181](https://user-images.githubusercontent.com/6006148/78899073-7d791300-7a3a-11ea-9f32-347a92b4f568.png)

Demo on Pixel 3 emulator seems to look correct with the icon from resources. Not really sure why it wouldn't for you though.

**Comment by wuilmerj24** [comment]
@bradmartin How big are the images?

**Comment by bradmartin** [comment]
I believe when I made the demo I grabbed the 24 versions from material icons website.

**Comment by Stanteq** [comment]
wuilmerj24, Using the font is better (like fontawesome) you will have more control over them.

**Comment by bradmartin** [comment]
`2.1.0` has been published which allows for the `scaleType` to be set on the FAB for android devices. Documentation on README for different values. This will help when using images in some cases for more fine control over the rendering.
