### ISSUE TITLE
FAB 2.0.1: font icons have different sizes on different screens

### ISSUE THREAD

**Issue by felixkrautschuk** [nstudio/nativescript-floatingactionbutton#117]
After upgrading to the latest version of the plugin **v. 2.0.1** it is hard to size the font icons correctly for different devices with different screens.

This is my css:
```
.fab-right {
    background-color: darkblue;
    color: white;
    height: 56;
    width: 56;
    margin: 0 15 15 0;
    horizontal-align: right;
    vertical-align: bottom;
}


.ns-android .fab-right {
    font-size: 10;
}
```

That's the result on Pixel 3a with Android 10:
<img width="426" alt="Bildschirmfoto 2020-06-04 um 17 11 06" src="https://user-images.githubusercontent.com/6443021/83775081-d655d800-a686-11ea-908d-0a365bed706c.png">

The first FAB on top has an PNG-icon from resources, the others use a FontAwesome icon.

Now the result on our ASUS ME173X with Android 4:
![Screenshot_2020-06-04-17-10-43](https://user-images.githubusercontent.com/6443021/83775479-45333100-a687-11ea-9be6-0e30dbf4371e.png)

So the FAB on top looks the same as on the Pixel 3a, but on the other FABs, the FontAwesome icon looks much smaller.

When setting a higher font-size, then the icons look as expected on the ASUS device, but they are far too big on the Pixel 3a.

Maybe the scale type should be configable instead of setting it statically [here](https://github.com/nstudio/nativescript-floatingactionbutton/commit/b6a0137f5167fe84e7ca48569eae3a43d8bd37d4)

The full sample app can be found here:
[ns-fab-issue-android.zip](https://github.com/nstudio/nativescript-floatingactionbutton/files/4731030/ns-fab-issue-android.zip)

**Comment by bradmartin** [comment]
Yeah that should help. You wanna help on a quick PR to allow an option to be passed for the scale type on Android? Should be straight forward for the most part.
