### ISSUE TITLE
Could not load view for: Fab.ReferenceError: NativeClass is not defined when used with {N} 7 with angular

### ISSUE THREAD

**Issue by Salahudeen** [nstudio/nativescript-floatingactionbutton#126]
Getting `Uncaught (in promise): TypeError: Could not load view for: Fab.ReferenceError: NativeClass is not defined `when used with {N} 7. 

I am registering the plugin on a shared UI module as below
```
import { registerElement } from '@nativescript/angular';
registerElement(
  'Fab',
  () => require('@nstudio/nativescript-floatingactionbutton').Fab
);
```

Tried changing the import as below, but gets a different error. `TypeError: viewClass is not a constructor`

```
import { registerElement } from '@nativescript/angular';
registerElement('Fab', () =>
  import('@nstudio/nativescript-floatingactionbutton').then((f) => f.Fab)
);
```

here is the package.json file
```
    "@angular/animations": "~10.0.0",
    "@angular/common": "~10.0.0",
    "@angular/compiler": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@nativescript/angular": "^10.0.0",
    "@nativescript/core": "^7.0.0",
    "@nativescript/theme": "^2.3.3",
    "@nstudio/nativescript-floatingactionbutton": "^3.0.0"
```

**Comment by abcfoundry** [comment]
Ya we are getting the same error.  If you find any details let me know...

**Comment by PhilippS93** [comment]
Same here

**Comment by bradmartin** [comment]
Looks like we had a bad publish, will try to republish ASAP.

**Comment by bradmartin** [comment]
`3.0.1` published with fix.

**Comment by Salahudeen** [comment]
@bradmartin, It still doesnt work....I get the following error

System.err: Error: Uncaught (in promise): TypeError: viewClass is not a constructor
System.err: TypeError: viewClass is not a constructor

**Comment by bradmartin** [comment]
Demo app seems to be running with the latest. This could be a different issue. Could you provide more of the stack?

**Comment by Salahudeen** [comment]
@bradmartin you are right, the demo app work fine, but its not working with {N} 7 and angular. Created the basic {N} project using schematics, added the plugin and issue is replicable. [Repo with issue](https://github.com/Salahudeen/nativescript-fab-issue). Please take a look.

My {N} cli version is 7.0.7

**Comment by PhilippS93** [comment]
Confirm, not working with N7 and Angular 10. No button is shown in my project.

**Comment by bradmartin** [comment]
Try with `3.0.2` just published and let me know if it works now.

**Comment by bradmartin** [comment]
<img width="1206" alt="kd" src="https://user-images.githubusercontent.com/6006148/94021184-5bb9e100-fd79-11ea-9c2f-1fcc60d028f4.png">

Also, you can do the registerElement call with this in your AppModule:

```typescript
import { Fab } from "@nstudio/nativescript-floatingactionbutton";

registerElement("Fab", () => Fab);
```

**Comment by PhilippS93** [comment]
Now, it is working again, thanks!

**Comment by Salahudeen** [comment]
Works like a charm! Thank you @bradmartin.
