### ISSUE TITLE
 FAB.TypeError: core_1.Property is not a constructor

### ISSUE THREAD

**Issue by Skillnter** [nstudio/nativescript-floatingactionbutton#127]
Followed all steps from here https://github.com/nstudio/nativescript-floatingactionbutton

Unable to understand, what is going wrong.

```
LOG from device Galaxy Note10+: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
LOG from device Galaxy Note10+: }
LOG from device Galaxy Note10+: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: FAB.TypeError: core_1.Property is not a constructor
LOG from device Galaxy Note10+: TypeError: Could not load view for: FAB.TypeError: core_1.Property is not a constructor
LOG from device Galaxy Note10+: at ViewUtil.createView (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/angular/view-util.js:214:44)
LOG from device Galaxy Note10+: at Object.getViewClass (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/angular/element-registry.js:84:15)
LOG from device Galaxy Note10+: at NativeScriptRenderer.createElement (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/angular/renderer.js:138:30)
LOG from device Galaxy Note10+: at DebugRenderer2.createElement (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bundles/core.umd.js:30492:36)
LOG from device Galaxy Note10+: at createElement (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bundles/core.umd.js:28524:31)
LOG from device Galaxy Note10+: at createViewNodes (file:///data/data/org.nativescript.preview/files/app/tns_modules/@angular/core/bund...
File change detected. Starting incremental webpack compilation...
```

HTML 
```
<ActionBar>
    <!-- 
    Use the NavigationButton as a side-drawer button in Android
    because ActionItems are shown on the right side of the ActionBar
    -->
    <NavigationButton ios:visibility="collapsed" icon="res://menu" (tap)="onDrawerButtonTap()"></NavigationButton>
    <!-- 
    Use the ActionItem for IOS with position set to left. Using the
    NavigationButton as a side-drawer button in iOS is not possible,
    because its function is to always navigate back in the application.
    -->
    <ActionItem icon="res://menu" android:visibility="collapsed" (tap)="onDrawerButtonTap()"
        ios.position="left">
    </ActionItem>
    <Label text="Browse"></Label>
</ActionBar>

<GridLayout class="page__content">
    <Label class="page__content-icon far" text="&#xf1ea;"></Label>
    <Label class="page__content-placeholder" text="<!-- Page content goes here -->"></Label>
    <StackLayout>
        <FAB (tap)="fabTap()" icon="'~/images/ic_add_white.png'" rippleColor="#f1f1f1" class="fab-button"></FAB>
    </StackLayout>
</GridLayout>
```

component.ts
```
import { Component, OnInit } from "@angular/core";
import { RadSideDrawer } from "nativescript-ui-sidedrawer";
import * as app from "tns-core-modules/application";

@Component({
    selector: "tt",
    templateUrl: "./tt.component.html"
})
export class ttComponent implements OnInit {

    constructor() {
        // Use the component constructor to inject providers.
    }

    ngOnInit(): void {
        // Init your component properties here.
    }

    onDrawerButtonTap(): void {
        const sideDrawer = <RadSideDrawer>app.getRootView();
        sideDrawer.showDrawer();
    }

    fabTap(){}
}

```
main.ts

```
// this import should be first in order to load some required settings (like globals and reflect-metadata)
import { platformNativeScriptDynamic } from "nativescript-angular/platform";

import { AppModule } from "./app/app.module";

import { registerElement } from 'nativescript-angular/element-registry';
registerElement(
  'Fab',
  () => require('@nstudio/nativescript-floatingactionbutton').Fab
);


platformNativeScriptDynamic().bootstrapModule(AppModule);
```
tried adding registerelement thing on Appcomponent and ttComponent too but no luck

**Comment by bradmartin** [comment]
Can you try the latest version `3.0.1` and see if that resolves the issue. Also need to see your package.json to confirm you're on NS7 or prior.

**Comment by Skillnter** [comment]
{
  "nativescript": {
    "id": "org.nativescript.networkdr",
    "tns-ios": {
      "version": "6.5.0"
    },
    "tns-android": {
      "version": "6.5.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-floatingactionbutton": "^3.0.1",
    "moment": "^2.28.0",
    "nativescript-accordion": "^6.0.0-beta.2",
    "nativescript-angular": "~8.21.0",
    "nativescript-ui-listview": "^8.2.0",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "~1.5.0",
    "node-sass": "^4.7.1",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  }
}

**Comment by Skillnter** [comment]
> Can you try the latest version `3.0.1` and see if that resolves the issue. Also need to see your package.json to confirm you're on NS7 or prior.

with version 2

> System.err: An uncaught Exception occurred on "main" thread.
> System.err: Calling js method onCreateView failed
> System.err: Error: android.content.res.Resources$NotFoundException: Resource ID #0x0
> System.err:
> System.err: StackTrace:
> System.err: push.../node_modules/@nstudio/nativescript-floatingactionbutton/fab.js.Fab.<computed>(file: node_modules\@nstudio\nativescript-floatingactionbutton\fab.android.js:83:0)
> System.err:     at applyAllNativeSetters(file: node_modules\@nativescript\core\ui\core\properties\properties.js:1048:0)
> System.err:     at initNativeView(file: node_modules\@nativescript\core\ui\core\properties\properties.js:992:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onResumeNativeUpdates(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:647:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._resumeNativeUpdates(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:278:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:232:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file: node_modules\@nativescript\core\ui\core\view\view.android.js:249:0)
> System.err:     at push.../node_modules/@nstudio/nativescript-floatingactionbutton/fab-common.js.FloatingActionButtonBase.onLoaded(file: node_modules\@nstudio\nativescript-floatingactionbutton\fab-common.js:15:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:75)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:310:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:456:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:234:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:925:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:233:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file: node_modules\@nativescript\core\ui\core\view\view.android.js:249:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:75)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:310:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:456:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:234:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:925:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:233:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file: node_modules\@nativescript\core\ui\core\view\view.android.js:249:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:75)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:310:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:456:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:234:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:925:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:233:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file: node_modules\@nativescript\core\ui\core\view\view.android.js:249:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:75)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:310:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:456:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:234:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/content-view/content-view.js.ContentView.eachChildView(file: node_modules\@nativescript\core\ui\content-view\content-view.js:70:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/page/page-common.js.PageBase.eachChildView(file: node_modules\@nativescript\core\ui\page\page-common.js:126:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:925:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:233:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file: node_modules\@nativescript\core\ui\core\view\view.android.js:249:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/page/page.js.Page.onLoaded(file: node_modules\@nativescript\core\ui\page\page.android.js:43:0)
> System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:75)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:310:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:317:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:456:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addViewCore(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:451:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addView(file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:437:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView(file: node_modules\@nativescript\core\ui\frame\frame.android.js:700:0)
> System.err:     at push.../node_modules/@nativescript/core/ui/frame/fragment.js.FragmentClass.onCreateView(file: node_modules\@nativescript\core\ui\frame\fragment.android.js:29:0)
> System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
> System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
> System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
> System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
> System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
> System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
> System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
> System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
> System.err:     at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
> System.err:     at android.os.Handler.handleCallback(Handler.java:883)
> System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
> System.err:     at android.os.Looper.loop(Looper.java:214)
> System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
> System.err:     at java.lang.reflect.Method.invoke(Native Method)
> System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> System.err: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
> System.err:     at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
> System.err:     at android.content.res.Resources.getDrawableForDensity(Resources.java:905)
> System.err:     at android.content.res.Resources.getDrawable(Resources.java:845)
> System.err:     at android.content.res.Resources.getDrawable(Resources.java:820)
> System.err:     ... 24 more

**Comment by bradmartin** [comment]
Okay so yeah you're not on the latest NS, so you do need to use the older `2x` version (note on README should be there). 

This error: ```System.err: Error: android.content.res.Resources$NotFoundException: Resource ID #0x0``` is telling us that the icon you're trying to use is not in your application when it's built.

I would look at your webpack config and be sure that the glob `images/` is there so that your image files are being bundled into the application.

**Comment by Skillnter** [comment]
> Okay so yeah you're not on the latest NS, so you do need to use the older `2x` version (note on README should be there).
> 
> This error: `System.err: Error: android.content.res.Resources$NotFoundException: Resource ID #0x0` is telling us that the icon you're trying to use is not in your application when it's built.
> 
> I would look at your webpack config and be sure that the glob `images/` is there so that your image files are being bundled into the application.

Images were present in the folder but I guess there was an issue exporting new files.

Worked after running the following commands:
`$tns platform clean android`

`$tns run android`


Thanks. It worked after cleaning everything and make a clean build with the version 2.
