### ISSUE TITLE
Display the action items when Fab Button is clicked - Nativescript7 Angular10

### ISSUE THREAD

**Issue by gitalvininfo** [nstudio/nativescript-floatingactionbutton#129]
Sorry in advance if I miss something with documentation(Angular version of this plugin) but I am confused right now.

I'm currently on my development of angular/nativescript app and I want to achieve the behaviour of the image below. 

![hYU28](https://user-images.githubusercontent.com/14288144/100972202-59db7d80-3573-11eb-9b91-5b640b2d72b7.jpg)

I follow the documentation for angular version like so, this is my **app.component.ts**
 
`import { registerElement } from 'nativescript-angular/element-registry';
registerElement(
    'Fab',
    () => require('@nstudio/nativescript-floatingactionbutton').Fab
);`

This is my view **app.component.html**

`<StackLayout>
    <FAB (tap)="fabTap()" icon="'~/images/ic_add_white.png'" rippleColor="#f1f1f1" class="fab-button"></FAB>
</StackLayout>`

I've manage to display the fab button and the next step is to display the action items when Fab Button is click like in the image attach.

I cannot find in the documentation how to achieve this one (Angular version) but I found a link [here](https://play.nativescript.org/?template=play-ng&id=zlJlTk) to which I think would direct to the solution but it uses something like a `<FabItem></FabItem>` which I am confused. 

**Nativescript Version - "@nativescript/core": "~7.0.0",
Angular Version - Version 10 - "@angular/core": "~10.1.0",**

Please tell me if this is possible or tell me if I miss something in documentation. I am new to nativescript development so a little bit of advice would be helpful

Thanks in advance.

**Comment by bradmartin** [comment]
Hey @gitalvininfo this was never implemented in the plugin. There are several ways to achieve this though.

One approach I did many years ago, when the plugin was initially built to add the FAB component, was to position buttons behind the FAB and then animate them out on the tap event :) https://www.youtube.com/watch?v=3n8cuJZmOvw

There are other ways as well... some in these youtube videos https://www.youtube.com/results?search_query=nativescript+FAB

**Comment by gitalvininfo** [comment]
Thanks for your response. Guess I'll start packing up and review my forgotten skills in css. 😆

**Comment by gitalvininfo** [comment]
**CLOSED**
