### ISSUE TITLE
FAB creates error messages in Android 8.0

### ISSUE THREAD

**Issue by erkanarslan** [nstudio/nativescript-floatingactionbutton#70]
When I visit a page that contains a FAB, I get this error in the console. It doesn't stop the application but I think it causes a little bit slow down. This doesn't happen on iOS.

Console messages are:

````
01-05 22:29:34.291 16931 16931 W LayerDrawable: 	at com.tns.Runtime.callJSMethodNative(Native Method)
01-05 22:29:34.291 16931 16931 W LayerDrawable: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
01-05 22:29:34.291 16931 16931 W LayerDrawable: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
01-05 22:29:34.291 16931 16931 W LayerDrawable: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
01-05 22:29:34.291 16931 16931 W LayerDrawable: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
01-05 22:29:34.291 16931 16931 W LayerDrawable: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
````

**Comment by r0zar** [comment]
Also see this. any update?

**Comment by tigrenok00** [comment]
Happens to me too, with tns 3.4.2 and FAB version 4.1.3

**Comment by bradmartin** [comment]
I never did get with the core team on this. Originally this issue (https://github.com/bradmartin/nativescript-floatingactionbutton/issues/57#issuecomment-331425213) was brought up and some changes were made to the core-modules of NS to fix and then these errors were always being logged.

Might be worth raising the issue on the core-modules again, if someone will do that,link this issue and tag me please.
