### ISSUE TITLE
Icon Scale Type

### ISSUE THREAD

**Issue by DanLatimer** [nstudio/nativescript-floatingactionbutton#98]
Hi,

I recently updated to {N} 6 and hence updated my nativescript-floatingactionbutton library and all my icons were too large and didn't fit in my fabs anymore.

I found a PR which changed the android scale type that is used which I believe is the culprit. Thought I would document that issue here for others that are having that problem.

https://github.com/nstudio/nativescript-floatingactionbutton/blob/a6b2cbb171dc78ee9cd3279a6602b416e802a9e8/src/fab.android.ts#L36

I was able to fix this issue by grabbing the fab using ViewChild, then accessing it's native element and setting the scale type to not only CENTER but CENTER_INSIDE

```
@ViewChild('fab', {static: true}) private fab1: ElementRef;
// ...
this.fab1.nativeElement.android.setScaleType(android.widget.ImageView.ScaleType.CENTER_INSIDE);
```

hope this makes things easier on the next person who has this issue

**Comment by DanLatimer** [comment]
Created a PR to fix this issue: https://github.com/nstudio/nativescript-floatingactionbutton/pull/99

**Comment by DanLatimer** [comment]
Until the PR is merged if anyone else has this issue they can get around it the way that I had to... extend the Fab object provided by the library, implement the initNativeView function to call the super then set the proper scaletype, then register your extended class.

```
import { Fab } from '@nstudio/nativescript-floatingactionbutton'

class WorkingFab extends Fab {
  // This hack is required until @nstudio accepts this pull request: https://github.com/nstudio/nativescript-floatingactionbutton/issues/98
  // otherwise the icons in fab buttons are not scaled properlly and can be way too big
  public initNativeView(): void {
    super.initNativeView();
    this.android.setScaleType(android.widget.ImageView.ScaleType.CENTER_INSIDE);
  }
}

registerElement('Fab', () => WorkingFab);
```

**Comment by anki247** [comment]
@DanLatimer thank you 👍

**Comment by bradmartin** [comment]
`1.0.1` published with PR 👍
